[project]
name = "al-adventure-catalog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bs4>=0.0.2",
    "dotenv>=0.9.9",
    "requests>=2.32.5",
    "word2number>=1.1",
]
